language: python
python:
  - 2.6
before_install:
  - which virtualenv
  - which python
  - head $(which virtualenv)
  - mkdir foo
  - cd foo
  - ASDF=GHJK
script:
  - pwd
  - echo $ASDF
  - ./fetch-and-build-2.4.sh
  