language: python
python:
  - 2.6
before_install:
  - python -c 'import sys; print sys.path'
  - python -c 'import numpy; print numpy.__file__'
install:
  - pip install http://switch.dl.sourceforge.net/project/numpy/NumPy/${NUMPY_VER}/numpy-1.7.0b2.tar.gz
script:
  - python -c 'import sys; print sys.path'
  - python -c 'import numpy; print numpy.__file__'
  