language: python
python:
  - 2.6
env:
  - TEST_VAR=foo
before_install:
  - set -v
  - echo "hello"
install:
  - if [ "$TEST_VAR" = "foo" ]; then echo ok; fi
  - mkdir foo
  - cd foo
  - ASDF=GHJK
script:
  - pwd
  - echo $ASDF
  - ./fetch-and-build-2.4.sh
  